debug: true

url: 'http://localhost:4000'
baseurl: &baseurl ''
analytics_tracking_id: false
apireference_url: &apireference_url 'http://datalogic.github.io/android-sdk-docs'
samples_url:
  astudio: 'https://github.com/datalogic/android-samples-astudio/tree/SDKv1'
  eclipse: 'https://github.com/datalogic/android-samples-eclipse/tree/SDKv1'
  apk: 'https://github.com/datalogic/android-samples-astudio/releases/'
